# Generated by Django 4.1.5 on 2023-01-06 14:49

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('meta_description', models.CharField(max_length=400)),
                ('meta_keywords', models.CharField(help_text='Add comma separated keywords from the blog', max_length=250)),
                ('subtitle', models.CharField(max_length=200, null=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='post/')),
                ('slug', models.SlugField(default='', editable=False, max_length=200)),
                ('publish_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('comment', models.TextField(max_length=1200)),
                ('show_comment', models.BooleanField(default=False)),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogpost')),
            ],
        ),
    ]
