# Generated by Django 4.1.5 on 2023-01-05 18:36

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blogpost_subtitle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=tinymce.models.HTMLField(),
        ),
    ]
